// <auto-generated />
using System;
using API_FeriadoAnbima.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_FeriadoAnbima.Migrations
{
    [DbContext(typeof(FeriadoAnbimaContext))]
    [Migration("20210809202458_DbAnbimaContext")]
    partial class DbAnbimaContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_FeriadoAnbima.Model.Feriado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<string>("diaDaSemana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("logDeRaspagemRequisicaoid")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("logDeRaspagemRequisicaoid");

                    b.ToTable("feriado");
                });

            modelBuilder.Entity("API_FeriadoAnbima.Model.LogDeRaspagemRequisicao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("anoSolicitado")
                        .HasColumnType("int");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<string>("descrição")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("enderecoHttps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isSucess")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("TB_LogDeRaspagemRequisicao");
                });

            modelBuilder.Entity("API_FeriadoAnbima.Model.Status", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("log")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("logDeRaspagemRequisicaoid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("logDeRaspagemRequisicaoid");

                    b.ToTable("status");
                });

            modelBuilder.Entity("API_FeriadoAnbima.Model.Feriado", b =>
                {
                    b.HasOne("API_FeriadoAnbima.Model.LogDeRaspagemRequisicao", "logDeRaspagemRequisicao")
                        .WithMany("feriados")
                        .HasForeignKey("logDeRaspagemRequisicaoid");

                    b.Navigation("logDeRaspagemRequisicao");
                });

            modelBuilder.Entity("API_FeriadoAnbima.Model.Status", b =>
                {
                    b.HasOne("API_FeriadoAnbima.Model.LogDeRaspagemRequisicao", "logDeRaspagemRequisicao")
                        .WithMany("status")
                        .HasForeignKey("logDeRaspagemRequisicaoid");

                    b.Navigation("logDeRaspagemRequisicao");
                });

            modelBuilder.Entity("API_FeriadoAnbima.Model.LogDeRaspagemRequisicao", b =>
                {
                    b.Navigation("feriados");

                    b.Navigation("status");
                });
#pragma warning restore 612, 618
        }
    }
}
